import type { ComponentCategory, RegistryEntry } from "./types.js";

export type { ComponentCategory, RegistryEntry };

export const CATEGORIES: ComponentCategory[] = [
  "Primitives",
  "Forms",
  "Layout",
  "Feedback",
  "Overlays",
  "Navigation",
  "Data Display",
  "AI",
];

const docs = (slug: string) => `https://www.kernelui.com/components/${slug}/`;

export const components: RegistryEntry[] = [
  {
    name: "Accordion",
    category: "Data Display",
    slug: "accordion",
    element: "<details> + <summary>",
    summary: "Native disclosure, exclusive open via a shared name.",
    status: "available",
    reactExports: ["Accordion", "AccordionItem"],
    elementTag: "kernel-accordion",
    elementSubTags: ["kernel-accordion-item"],
    docsUrl: docs("accordion"),
    shadcnAliases: ["accordion", "collapsible"],
    radixPackages: ["@radix-ui/react-accordion", "@radix-ui/react-collapsible"],
    migrationCaveats: [
      "Radix Accordion uses controlled value/onValueChange on the root; Kernel AccordionItem uses title + defaultOpen per item.",
      "No Radix-style AccordionTrigger/AccordionContent composition — pass title and children to AccordionItem.",
    ],
  },
  {
    name: "Avatar",
    category: "Primitives",
    slug: "avatar",
    element: "<img>",
    summary: "Real image, with an initials fallback.",
    status: "available",
    reactExports: ["Avatar"],
    elementTag: "kernel-avatar",
    docsUrl: docs("avatar"),
    shadcnAliases: ["avatar"],
    radixPackages: ["@radix-ui/react-avatar"],
  },
  {
    name: "Badge",
    category: "Primitives",
    slug: "badge",
    element: "<span>",
    summary: "A small status chip.",
    status: "available",
    reactExports: ["Badge"],
    elementTag: "kernel-badge",
    docsUrl: docs("badge"),
    shadcnAliases: ["badge"],
  },
  {
    name: "Breadcrumbs",
    category: "Navigation",
    slug: "breadcrumbs",
    element: '<nav aria-label="breadcrumb"> + <ol>',
    summary: "Ordered trail, aria-current for the current page.",
    status: "available",
    reactExports: ["Breadcrumbs", "BreadcrumbItem", "BreadcrumbsTrail"],
    elementTag: "kernel-breadcrumbs",
    elementSubTags: ["kernel-breadcrumb-item"],
    docsUrl: docs("breadcrumbs"),
    shadcnAliases: ["breadcrumb"],
  },
  {
    name: "Button",
    category: "Primitives",
    slug: "button",
    element: "<button>",
    summary: "Click, keyboard, and form association, for free.",
    status: "available",
    reactExports: ["Button"],
    elementTag: "kernel-button",
    docsUrl: docs("button"),
    shadcnAliases: ["button"],
    radixPackages: ["@radix-ui/react-slot"],
    migrationCaveats: [
      "shadcn asChild maps to Kernel's render prop: <Button render={<a href=\"...\" />}>.",
    ],
  },
  {
    name: "Callout",
    category: "Feedback",
    slug: "callout",
    element: 'role="alert" / role="status"',
    summary: "Live-region feedback that announces itself.",
    status: "available",
    reactExports: ["Callout"],
    elementTag: "kernel-callout",
    docsUrl: docs("callout"),
    shadcnAliases: ["alert"],
  },
  {
    name: "Card",
    category: "Layout",
    slug: "card",
    element: "<article> / <div>",
    summary: "For genuinely self-contained, distributable content.",
    status: "available",
    reactExports: ["Card", "CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    elementTag: "kernel-card",
    elementSubTags: [
      "kernel-card-header",
      "kernel-card-title",
      "kernel-card-description",
      "kernel-card-content",
      "kernel-card-footer",
    ],
    docsUrl: docs("card"),
    shadcnAliases: ["card"],
  },
  {
    name: "Carousel",
    category: "Data Display",
    slug: "carousel",
    element: "scroll-snap-type / scroll-snap-align",
    summary: "Native scrolling instead of a JS carousel engine.",
    status: "available",
    reactExports: ["Carousel", "CarouselSlide"],
    elementTag: "kernel-carousel",
    elementSubTags: ["kernel-carousel-slide"],
    docsUrl: docs("carousel"),
    shadcnAliases: ["carousel"],
    radixPackages: ["embla-carousel-react"],
  },
  {
    name: "Checkbox",
    category: "Primitives",
    slug: "checkbox",
    element: '<input type="checkbox">',
    summary: "Tri-state, styled with :checked and :indeterminate.",
    status: "available",
    reactExports: ["Checkbox"],
    elementTag: "kernel-checkbox",
    docsUrl: docs("checkbox"),
    shadcnAliases: ["checkbox"],
    radixPackages: ["@radix-ui/react-checkbox"],
    migrationCaveats: ["onCheckedChange naming matches Radix; value API uses checked/defaultChecked/onCheckedChange."],
  },
  {
    name: "Color Picker",
    category: "Forms",
    slug: "color-picker",
    element: '<input type="color"> + editable hex <input>',
    summary: "A real colour input, plus a typeable hex field on the same value.",
    status: "available",
    reactExports: ["ColorPicker"],
    elementTag: "kernel-color-picker",
    docsUrl: docs("color-picker"),
  },
  {
    name: "Combobox",
    category: "Forms",
    slug: "combobox",
    element: '<input role="combobox"> + popover listbox',
    summary: "Filterable list with aria-activedescendant.",
    status: "available",
    reactExports: ["Combobox"],
    elementTag: "kernel-combobox",
    docsUrl: docs("combobox"),
    shadcnAliases: ["combobox", "command"],
    radixPackages: ["@radix-ui/react-select", "cmdk"],
    migrationCaveats: [
      "Custom Radix/shadcn Select with search/filter usually maps here, not native Select.",
      "Options are passed as an options prop array, not SelectItem children.",
    ],
  },
  {
    name: "Command Palette",
    category: "Overlays",
    slug: "command-palette",
    element: '<dialog> + <input> + role="listbox"',
    summary: "A searchable, keyboard-driven action list.",
    status: "available",
    reactExports: ["CommandPalette"],
    elementTag: "kernel-command-palette",
    docsUrl: docs("command-palette"),
    shadcnAliases: ["command"],
    radixPackages: ["cmdk"],
  },
  {
    name: "Composer",
    category: "AI",
    slug: "composer",
    element: "<textarea> with field-sizing: content",
    summary: 'A chat message input, with a live "thinking" state.',
    status: "available",
    reactExports: ["Composer"],
    elementTag: "kernel-composer",
    docsUrl: docs("composer"),
  },
  {
    name: "Context Menu",
    category: "Overlays",
    slug: "context-menu",
    element: 'role="menu" at cursor position',
    summary: "Right-click menu, same primitives as Dropdown Menu.",
    status: "available",
    reactExports: ["ContextMenu"],
    elementTag: "kernel-context-menu",
    docsUrl: docs("context-menu"),
    shadcnAliases: ["context-menu"],
    radixPackages: ["@radix-ui/react-context-menu"],
  },
  {
    name: "Data Table",
    category: "Data Display",
    slug: "data-table",
    element: "<table> + sort/filter/paginate",
    summary: "Table plus the behaviour layered on top.",
    status: "available",
    reactExports: ["DataTable"],
    elementTag: "kernel-data-table",
    docsUrl: docs("data-table"),
    shadcnAliases: ["data-table", "table"],
    migrationCaveats: ["TanStack Table column definitions differ; Kernel DataTable takes a columns prop with a simpler API."],
  },
  {
    name: "Date Picker",
    category: "Data Display",
    slug: "date-picker",
    element: "<table> grid of <button> day cells",
    summary: "Calendar grid with aria-selected.",
    status: "available",
    reactExports: ["DatePicker"],
    elementTag: "kernel-date-picker",
    docsUrl: docs("date-picker"),
    shadcnAliases: ["calendar", "date-picker"],
    radixPackages: ["react-day-picker"],
  },
  {
    name: "Date Range Picker",
    category: "Data Display",
    slug: "date-range-picker",
    element: "<table> grid of <button> day cells",
    summary: "Two-click range selection over the same calendar grid.",
    status: "available",
    reactExports: ["DateRangePicker"],
    elementTag: "kernel-date-range-picker",
    docsUrl: docs("date-range-picker"),
    shadcnAliases: ["date-range-picker"],
  },
  {
    name: "Dialog",
    category: "Overlays",
    slug: "dialog",
    element: "<dialog>",
    summary: "showModal(): focus trap, top layer, and ::backdrop, free.",
    status: "available",
    reactExports: ["Dialog"],
    elementTag: "kernel-dialog",
    docsUrl: docs("dialog"),
    shadcnAliases: ["dialog", "alert-dialog"],
    radixPackages: ["@radix-ui/react-dialog", "@radix-ui/react-alert-dialog"],
    migrationCaveats: [
      "Kernel Dialog is a single component with title/description/children props — not Dialog.Root/Trigger/Portal/Content.",
      "shadcn Alert Dialog is this component with closeOnBackdropClick={false}. shadcn Sheet is Kernel Sheet, which adds drag-to-dismiss on top of this.",
    ],
  },
  {
    name: "Dropdown Menu",
    category: "Overlays",
    slug: "dropdown-menu",
    element: 'popover + role="menu"',
    summary: "Anchor-positioned menu with arrow-key navigation.",
    status: "available",
    reactExports: ["DropdownMenu", "MenuItem", "MenuSeparator"],
    elementTag: "kernel-dropdown-menu",
    elementSubTags: ["kernel-menu-item", "kernel-menu-separator"],
    docsUrl: docs("dropdown-menu"),
    shadcnAliases: ["dropdown-menu", "menubar"],
    radixPackages: ["@radix-ui/react-dropdown-menu", "@radix-ui/react-menubar"],
    migrationCaveats: ["Use render prop instead of asChild on the trigger: <DropdownMenu render={<Button />}>."],
  },
  {
    name: "File Upload",
    category: "Forms",
    slug: "file-upload",
    element: '<label> + <input type="file">',
    summary: "Drag-and-drop over a real file input, with optional square image preview moulding.",
    llmsNote:
      '`onError` fires with `type: "accept" | "max-size" | "max-files" | "directory"` when a pick or drop is rejected (including a dropped folder, which the platform surfaces as an unreadable 0-byte `File`).',
    status: "available",
    reactExports: ["FileUpload"],
    elementTag: "kernel-file-upload",
    docsUrl: docs("file-upload"),
  },
  {
    name: "Footer",
    category: "Layout",
    slug: "footer",
    element: "<footer>",
    summary: "The contentinfo landmark.",
    status: "available",
    reactExports: ["Footer"],
    elementTag: "kernel-footer",
    docsUrl: docs("footer"),
  },
  {
    name: "Header",
    category: "Layout",
    slug: "header",
    element: "<header>",
    summary: "The banner landmark.",
    status: "available",
    reactExports: ["Header"],
    elementTag: "kernel-header",
    docsUrl: docs("header"),
  },
  {
    name: "Hover Card",
    category: "Overlays",
    slug: "hover-card",
    element: "popover=hint / interestfor",
    summary: "Rich hover preview, a heavier Tooltip.",
    status: "available",
    reactExports: ["HoverCard"],
    elementTag: "kernel-hover-card",
    docsUrl: docs("hover-card"),
    shadcnAliases: ["hover-card"],
    radixPackages: ["@radix-ui/react-hover-card"],
  },
  {
    name: "Input OTP",
    category: "Forms",
    slug: "input-otp",
    element: "a row of real <input>",
    summary: "One-time-code entry with roving focus.",
    status: "available",
    reactExports: ["InputOTP"],
    elementTag: "kernel-input-otp",
    docsUrl: docs("input-otp"),
    shadcnAliases: ["input-otp"],
    radixPackages: ["input-otp"],
  },
  {
    name: "Label",
    category: "Primitives",
    slug: "label",
    element: "<label>",
    summary: "A standalone label for custom composed controls.",
    status: "available",
    reactExports: ["Label"],
    elementTag: "kernel-label",
    docsUrl: docs("label"),
    shadcnAliases: ["label"],
    radixPackages: ["@radix-ui/react-label"],
  },
  {
    name: "Nav",
    category: "Layout",
    slug: "nav",
    element: "<nav> + <ul>",
    summary: "Active state via aria-current, no client JS.",
    status: "available",
    reactExports: ["Nav", "NavLink"],
    elementTag: "kernel-nav",
    elementSubTags: ["kernel-nav-link"],
    docsUrl: docs("nav"),
  },
  {
    name: "Navigation Menu",
    category: "Overlays",
    slug: "navigation-menu",
    element: "<nav> + nested disclosure",
    summary: "Multi-level site navigation, mega-menu via popover.",
    status: "available",
    reactExports: [
      "NavigationMenu",
      "NavigationMenuItem",
      "NavigationMenuLink",
      "NavigationMenuTrigger",
      "NavigationMenuContent",
    ],
    elementTag: "kernel-navigation-menu",
    elementSubTags: [
      "kernel-nav-menu-item",
      "kernel-nav-menu-link",
      "kernel-nav-menu-trigger",
      "kernel-nav-menu-content",
    ],
    docsUrl: docs("navigation-menu"),
    shadcnAliases: ["navigation-menu"],
    radixPackages: ["@radix-ui/react-navigation-menu"],
  },
  {
    name: "Number Field",
    category: "Forms",
    slug: "number-field",
    element: '<input type="number"> + native stepUp()/stepDown()',
    summary: "TextField's scaffold, specialised for numbers.",
    status: "available",
    reactExports: ["NumberField"],
    elementTag: "kernel-number-field",
    docsUrl: docs("number-field"),
  },
  {
    name: "Pagination",
    category: "Navigation",
    slug: "pagination",
    element: '<nav aria-label="pagination"> + <ol>',
    summary: "Ordered page links, aria-current for the active one.",
    status: "available",
    reactExports: ["Pagination", "PaginationItem", "PaginationPrevious", "PaginationNext", "PaginationEllipsis"],
    elementTag: "kernel-pagination",
    elementSubTags: [
      "kernel-pagination-item",
      "kernel-pagination-previous",
      "kernel-pagination-next",
      "kernel-pagination-ellipsis",
    ],
    docsUrl: docs("pagination"),
    shadcnAliases: ["pagination"],
  },
  {
    name: "Popover",
    category: "Overlays",
    slug: "popover",
    element: "popover + anchor positioning",
    summary: "Anchor-positioned floating panel.",
    status: "available",
    reactExports: ["Popover"],
    elementTag: "kernel-popover",
    docsUrl: docs("popover"),
    shadcnAliases: ["popover"],
    radixPackages: ["@radix-ui/react-popover"],
    migrationCaveats: ["Use render prop on the trigger instead of asChild."],
  },
  {
    name: "Progress",
    category: "Feedback",
    slug: "progress",
    element: "<progress>",
    summary: "Reports its own value to assistive tech, natively.",
    status: "available",
    reactExports: ["Progress"],
    elementTag: "kernel-progress",
    docsUrl: docs("progress"),
    shadcnAliases: ["progress"],
    radixPackages: ["@radix-ui/react-progress"],
  },
  {
    name: "Radio Group",
    category: "Primitives",
    slug: "radio-group",
    element: '<fieldset> + <input type="radio">',
    summary: "Grouped choice with native arrow-key roving.",
    status: "available",
    reactExports: ["RadioGroup", "RadioGroupItem"],
    elementTag: "kernel-radio-group",
    elementSubTags: ["kernel-radio-group-item"],
    docsUrl: docs("radio-group"),
    shadcnAliases: ["radio-group"],
    radixPackages: ["@radix-ui/react-radio-group"],
  },
  {
    name: "Reasoning",
    category: "AI",
    slug: "reasoning",
    element: "<details> + <summary>",
    summary: "A collapsible AI reasoning trace that auto-opens while streaming.",
    status: "available",
    reactExports: ["Reasoning"],
    elementTag: "kernel-reasoning",
    docsUrl: docs("reasoning"),
  },
  {
    name: "Resizable",
    category: "Layout",
    slug: "resizable",
    element: "CSS resize / pointer-driven splitters",
    summary: "Pane-to-pane split layouts.",
    status: "available",
    reactExports: ["Resizable"],
    elementTag: "kernel-resizable",
    docsUrl: docs("resizable"),
    shadcnAliases: ["resizable"],
    radixPackages: ["react-resizable-panels"],
  },
  {
    name: "Scroll Area",
    category: "Layout",
    slug: "scroll-area",
    element: "native scroll + scrollbar-gutter",
    summary: "Custom scrollbar styling as enhancement only.",
    status: "available",
    reactExports: ["ScrollArea"],
    elementTag: "kernel-scroll-area",
    docsUrl: docs("scroll-area"),
    shadcnAliases: ["scroll-area"],
    radixPackages: ["@radix-ui/react-scroll-area"],
  },
  {
    name: "Select",
    category: "Forms",
    slug: "select",
    element: "<select>",
    summary: "The platform's own picker UI, on every device.",
    status: "available",
    reactExports: ["Select", "SelectOption"],
    elementTag: "kernel-select",
    docsUrl: docs("select"),
    shadcnAliases: ["select"],
    radixPackages: ["@radix-ui/react-select"],
    migrationCaveats: [
      "Kernel Select wraps a native <select> — the OS renders the picker.",
      "Custom portal/listbox Select from Radix usually maps to Combobox instead.",
      "Use SelectOption (or real <option> in elements) instead of SelectItem.",
    ],
  },
  {
    name: "Separator",
    category: "Primitives",
    slug: "separator",
    element: "<hr>",
    summary: 'A divider that\'s already role="separator".',
    status: "available",
    reactExports: ["Separator"],
    elementTag: "kernel-separator",
    docsUrl: docs("separator"),
    shadcnAliases: ["separator"],
    radixPackages: ["@radix-ui/react-separator"],
  },
  {
    name: "Sheet",
    category: "Overlays",
    slug: "sheet",
    element: "<dialog> + pointer events",
    summary: "A Dialog anchored to an edge, with drag-to-dismiss.",
    llmsNote:
      "Takes every Dialog prop, with `side` narrowed to bottom/top/left/right and defaulting to `\"bottom\"`. Adds `showHandle`, `handleOnly` (set it when the body scrolls), `dismissible` (disables dragging and backdrop dismissal, not Escape), `closeThreshold`, `velocityThreshold`, `scrollLockTimeout`, `onDrag`, `onRelease`. There are no snap points — a Sheet is open or dismissed.",
    status: "available",
    reactExports: ["Sheet", "useSheetDrag"],
    elementTag: "kernel-sheet",
    docsUrl: docs("sheet"),
    shadcnAliases: ["sheet", "drawer"],
    radixPackages: ["vaul"],
    migrationCaveats: [
      "Replaces Vaul: Drawer.Root/Trigger/Portal/Overlay/Content/Handle collapse into one <Sheet> with open/onOpenChange, since a real <dialog> needs no portal and draws its own ::backdrop.",
      "Vaul's snapPoints/activeSnapPoint have no equivalent — a Sheet is either open or dismissed.",
      "direction becomes side; dismissible and handleOnly keep their names; closeThreshold, velocityThreshold, and scrollLockTimeout keep Vaul's defaults.",
    ],
  },
  {
    name: "Sidebar",
    category: "Layout",
    slug: "sidebar",
    element: "<aside>",
    summary: "The complementary landmark.",
    status: "available",
    reactExports: ["Sidebar"],
    elementTag: "kernel-sidebar",
    docsUrl: docs("sidebar"),
    shadcnAliases: ["sidebar"],
  },
  {
    name: "Skeleton",
    category: "Feedback",
    slug: "skeleton",
    element: '<div aria-hidden="true">',
    summary: "Loading placeholder tied to real content dimensions.",
    status: "available",
    reactExports: ["Skeleton"],
    elementTag: "kernel-skeleton",
    docsUrl: docs("skeleton"),
    shadcnAliases: ["skeleton"],
  },
  {
    name: "Slider",
    category: "Forms",
    slug: "slider",
    element: '<input type="range">',
    summary: "Custom-painted thumb, native drag and keyboard behaviour.",
    status: "available",
    reactExports: ["Slider"],
    elementTag: "kernel-slider",
    docsUrl: docs("slider"),
    shadcnAliases: ["slider"],
    radixPackages: ["@radix-ui/react-slider"],
  },
  {
    name: "Sources",
    category: "AI",
    slug: "sources",
    element: "<section> + <ul> of <a>",
    summary: "Cited sources and inline numbered citation chips for grounded answers.",
    status: "available",
    reactExports: ["Sources", "Source", "Citation"],
    elementTag: "kernel-sources",
    elementSubTags: ["kernel-source", "kernel-citation"],
    docsUrl: docs("sources"),
  },
  {
    name: "Switch",
    category: "Primitives",
    slug: "switch",
    element: '<button role="switch">',
    summary: "The WAI-ARIA switch pattern on a real button.",
    status: "available",
    reactExports: ["Switch"],
    elementTag: "kernel-switch",
    docsUrl: docs("switch"),
    shadcnAliases: ["switch"],
    radixPackages: ["@radix-ui/react-switch"],
    migrationCaveats: ["onCheckedChange naming matches Radix."],
  },
  {
    name: "Suggestion",
    category: "AI",
    slug: "suggestion",
    element: '<ul role="list"> of <button>',
    summary: "Prompt suggestion chips that seed the next composer message.",
    status: "available",
    reactExports: ["Suggestion", "SuggestionItem"],
    elementTag: "kernel-suggestion",
    elementSubTags: ["kernel-suggestion-item"],
    docsUrl: docs("suggestion"),
  },
  {
    name: "Table",
    category: "Data Display",
    slug: "table",
    element: "<table>",
    summary: "Sortable headers, real <caption>, real <th scope>.",
    status: "available",
    reactExports: ["Table", "TableCaption", "TableHeader", "TableBody", "TableRow", "TableHead", "TableCell"],
    elementTag: "kernel-table",
    elementSubTags: [
      "kernel-table-caption",
      "kernel-table-header",
      "kernel-table-body",
      "kernel-table-row",
      "kernel-table-head",
      "kernel-table-cell",
    ],
    docsUrl: docs("table"),
    shadcnAliases: ["table"],
  },
  {
    name: "Tabs",
    category: "Navigation",
    slug: "tabs",
    element: 'role="tablist"',
    summary: "No native element exists yet, ARIA APG pattern.",
    status: "available",
    reactExports: ["Tabs", "TabsList", "Tab", "TabPanel"],
    elementTag: "kernel-tabs",
    elementSubTags: ["kernel-tabs-list", "kernel-tab", "kernel-tab-panel"],
    docsUrl: docs("tabs"),
    shadcnAliases: ["tabs"],
    radixPackages: ["@radix-ui/react-tabs"],
    migrationCaveats: ["value/onValueChange API matches Radix; subcomponent names differ (Tab vs TabsTrigger)."],
  },
  {
    name: "Tag Input",
    category: "Forms",
    slug: "tag-input",
    element: 'role="list" of removable tags + trailing <input>',
    summary: "Freeform text that commits into discrete, removable tags.",
    status: "available",
    reactExports: ["TagInput"],
    elementTag: "kernel-tag-input",
    docsUrl: docs("tag-input"),
  },
  {
    name: "Text Field",
    category: "Forms",
    slug: "text-field",
    element: "<label> + <input>",
    summary: "Correct labelling and live validation styling.",
    status: "available",
    reactExports: ["TextField"],
    elementTag: "kernel-text-field",
    docsUrl: docs("text-field"),
    shadcnAliases: ["input"],
    migrationCaveats: [
      "label is required — use hideLabel for visually hidden labels.",
      "shadcn Input without a label needs a TextField with label + hideLabel.",
    ],
  },
  {
    name: "Textarea",
    category: "Forms",
    slug: "textarea",
    element: "<textarea>",
    summary: "Auto-growing with field-sizing: content.",
    status: "available",
    reactExports: ["Textarea"],
    elementTag: "kernel-textarea",
    docsUrl: docs("textarea"),
    shadcnAliases: ["textarea"],
    migrationCaveats: ["label is required — same form-field scaffold as TextField."],
  },
  {
    name: "Thinking Indicator",
    category: "AI",
    slug: "thinking-indicator",
    element: 'role="status"',
    summary: "The universal typing-indicator dots, next to real visible text.",
    status: "available",
    reactExports: ["ThinkingIndicator"],
    elementTag: "kernel-thinking-indicator",
    docsUrl: docs("thinking-indicator"),
  },
  {
    name: "Toast",
    category: "Feedback",
    slug: "toast",
    element: 'role="status" / role="alert" (queued)',
    summary: "A shared, queued live region.",
    status: "available",
    reactExports: ["ToastViewport", "toast"],
    elementTag: "kernel-toast-viewport",
    docsUrl: docs("toast"),
    shadcnAliases: ["toast", "sonner"],
    radixPackages: ["@radix-ui/react-toast", "sonner"],
    migrationCaveats: [
      "Mount <ToastViewport /> once, then call toast() from anywhere — similar to Sonner.",
    ],
  },
  {
    name: "Toggle",
    category: "Primitives",
    slug: "toggle",
    element: "<button aria-pressed>",
    summary: "A two-state toggle that looks and acts like a button.",
    status: "available",
    reactExports: ["Toggle"],
    elementTag: "kernel-toggle",
    docsUrl: docs("toggle"),
    shadcnAliases: ["toggle", "toggle-group"],
    radixPackages: ["@radix-ui/react-toggle", "@radix-ui/react-toggle-group"],
  },
  {
    name: "Tool Call",
    category: "AI",
    slug: "tool-call",
    element: "<details> + <summary>",
    summary: "Collapsible agent tool status with pending, running, complete, and error states.",
    status: "available",
    reactExports: ["ToolCall"],
    elementTag: "kernel-tool-call",
    docsUrl: docs("tool-call"),
  },
  {
    name: "Tooltip",
    category: "Overlays",
    slug: "tooltip",
    element: "popover + interestfor",
    summary: "Hover/focus hints via the Popover API.",
    status: "available",
    reactExports: ["Tooltip"],
    elementTag: "kernel-tooltip",
    docsUrl: docs("tooltip"),
    shadcnAliases: ["tooltip"],
    radixPackages: ["@radix-ui/react-tooltip"],
    migrationCaveats: ["Use render prop on the trigger instead of asChild."],
  },
];

export function getComponentBySlug(slug: string): RegistryEntry | undefined {
  return components.find((entry) => entry.slug === slug);
}

export function getComponentsByCategory(category: ComponentCategory): RegistryEntry[] {
  return components.filter((entry) => entry.category === category);
}

export function getAvailableComponents(): RegistryEntry[] {
  return components.filter((entry) => entry.status === "available");
}
