/**
 * The single place that reads or writes the site's theme. Anything
 * that lets a visitor change accent, radius, or colour scheme —
 * ThemePlayground's "try it here" demo, the header's ThemeMenu, the
 * sun/moon ThemeToggle — calls through here instead of touching
 * `<html>` directly, so a change made in any one of them is visible in
 * all the others immediately and survives navigation.
 *
 * The storage keys here are duplicated (by necessity, not by
 * accident) in the inline no-FOUC script in BaseLayout.astro's
 * `<head>`, which has to stay a synchronous, dependency-free snippet
 * to run before first paint — it can't `import` this module. Keep the
 * three key strings in sync if either one changes.
 */

/** Every gamut-checked preset generated by
 * packages/styles/scripts/generate-accent-themes.mjs. Verified against
 * OKLCH-converted reference swatches there, not eyeballed, so e.g.
 * "violet" is actually violet. */
export const ACCENTS = ["amber", "blue", "green", "red", "violet", "orange", "teal"] as const;
export type AccentName = (typeof ACCENTS)[number];

export interface RadiusOption {
  name: string;
  value: string;
  /** Pairs a `--kernel-radius-control` override with this base value —
   * "Round" is Kernel's own pill-controls brand treatment, which only
   * makes sense alongside a generous base radius. Sharp/Soft leave
   * `--kernel-radius-control` unset, so buttons/inputs/toggles fall
   * back to the natural `--kernel-radius-md` cascade like every other
   * radius tier — otherwise a site-wide pill override would silently
   * defeat this exact control for two-thirds of the presets. */
  control?: string;
}

export const RADII: RadiusOption[] = [
  { name: "Sharp", value: "0.1875rem" },
  { name: "Soft", value: "0.5rem" },
  { name: "Round", value: "1.25rem", control: "var(--kernel-radius-full)" },
];

export type ColorScheme = "light" | "dark";

const STORAGE_KEYS = {
  accent: "kernel:accent",
  radius: "kernel:radius",
  radiusControl: "kernel:radius-control",
  scheme: "kernel:color-scheme",
} as const;

/**
 * ThemePlayground, ThemeMenu, and ThemeToggle are three separate Astro
 * islands (three separate React roots) that can independently change
 * the theme — they can't share React state directly, and
 * `window.addEventListener("storage", ...)` only fires in *other*
 * tabs/windows, never the one that made the change. This event is the
 * same-page equivalent: every `apply*` call below dispatches it, and
 * anything that renders a theme control listens for it to stay in
 * sync with changes made anywhere else on the same page.
 */
export const THEME_CHANGE_EVENT = "kernel:theme-change";

function announce() {
  window.dispatchEvent(new Event(THEME_CHANGE_EVENT));
}

export function applyAccent(name: AccentName) {
  document.documentElement.setAttribute("data-kernel-accent", name);
  localStorage.setItem(STORAGE_KEYS.accent, name);
  announce();
}

export function applyRadius(radius: RadiusOption) {
  document.documentElement.style.setProperty("--kernel-radius-base", radius.value);
  localStorage.setItem(STORAGE_KEYS.radius, radius.value);
  if (radius.control) {
    document.documentElement.style.setProperty("--kernel-radius-control", radius.control);
    localStorage.setItem(STORAGE_KEYS.radiusControl, radius.control);
  } else {
    document.documentElement.style.removeProperty("--kernel-radius-control");
    localStorage.removeItem(STORAGE_KEYS.radiusControl);
  }
  announce();
}

export function applyColorScheme(scheme: ColorScheme) {
  document.documentElement.setAttribute("data-theme", scheme);
  localStorage.setItem(STORAGE_KEYS.scheme, scheme);
  announce();
}

export function getStoredAccent(): AccentName | null {
  const value = localStorage.getItem(STORAGE_KEYS.accent);
  return value && (ACCENTS as readonly string[]).includes(value) ? (value as AccentName) : null;
}

export function getStoredRadiusValue(): string | null {
  return localStorage.getItem(STORAGE_KEYS.radius);
}

/** `null` means "no override" — Sharp/Soft deliberately clear this key
 * so `--kernel-radius-control` falls back to its natural
 * `--kernel-radius-md` cascade instead of staying pinned to pill. */
export function getStoredRadiusControl(): string | null {
  return localStorage.getItem(STORAGE_KEYS.radiusControl);
}

/** The radius option name (Sharp/Soft/Round) matching whatever value is
 * currently stored, if any — lets a UI highlight the active choice
 * without also hand-storing the name alongside the value. */
export function getStoredRadiusName(): string | null {
  const value = getStoredRadiusValue();
  return RADII.find((radius) => radius.value === value)?.name ?? null;
}

export function getStoredColorScheme(): ColorScheme | null {
  const value = localStorage.getItem(STORAGE_KEYS.scheme);
  return value === "light" || value === "dark" ? value : null;
}
